version: "3.7"
services:
  proyectos_micro:
    container_name: proyectos_micro
    image: proyectos_micro:latest
    build:
      context: .
    ports:
      - "4002"
    networks:
      - proyectos-app

  proyectos_micro_2:
    container_name: proyectos_micro_2
    image: proyectos_micro:latest
    ports:
      - "4002"
    networks:
      - proyectos-app

  proyectos_micro_3:
    container_name: proyectos_micro_3
    image: proyectos_micro:latest
    ports:
      - "4002"
    networks:
      - proyectos-app

  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:latest
    build:
      context: ./balanceador
    ports:
      - "4004:80"
    networks:
      - proyectos-app

networks:
  proyectos-app:
