version: "3"

services:
  microservicio-back:
    container_name: microservicio-back
    restart: always
    build: .
    ports:
      - "5030:3030"
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongoms
    image: mongo
    ports:
      - "27030:27025"
